import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import shipmentsRouter from "./shipments";
import aiRouter from "./ai";
import carriersRouter from "./carriers";
import paymentsRouter from "./payments";
import notificationsRouter from "./notifications";
import dashboardRouter from "./dashboard";
import pricingRouter from "./pricing";
import usersRouter from "./users";
import squareRouter from "./square";
import corporateRouter from "./corporate";
import invoicesRouter from "./invoices";
import configRouter from "./config";
import financeRouter from "./finance";
import driverRouter from "./driver";
import aiSettingsRouter from "./ai-settings";
import marketingRouter from "./marketing";
import blogRouter from "./blog";
import contactsRouter from "./contacts";
import seoRouter from "./seo";
import vanRouter from "./van";
import vanExtrasRouter from "./van-extras";
import companyRouter from "./company";
import contractChatRouter from "./contract-chat";
import storageRouter from "./storage";
import userLogsRouter from "./user-logs";
import lineRouter from "./line";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(shipmentsRouter);
router.use(aiRouter);
router.use(carriersRouter);
router.use(paymentsRouter);
router.use(notificationsRouter);
router.use(dashboardRouter);
router.use(pricingRouter);
router.use(usersRouter);
router.use(squareRouter);
router.use(corporateRouter);
router.use(invoicesRouter);
router.use(configRouter);
router.use(financeRouter);
router.use(driverRouter);
router.use(aiSettingsRouter);
router.use(marketingRouter);
router.use(blogRouter);
router.use(contactsRouter);
router.use(seoRouter);
router.use(vanRouter);
router.use(vanExtrasRouter);
router.use(companyRouter);
router.use(contractChatRouter);
router.use(storageRouter);
router.use(userLogsRouter);
router.use(lineRouter);

export default router;
